model: 'geonet'
downstage: 4
task: 'prec'
c_in: 7
n_lgab: 16
c_lgan: 90
window_sizes: [ 5,10 ]
num_heads: 4
down_sample: 4
r_expand: 2

fp: 32
loss: 'nn.SmoothL1Loss()'
optimizer: 'AdamW'
pretrain:
resume:
batch_size: 6
balanced_gpu0: -1
epochs: 100
lr: 0.001
#decays: [5,10,15]
decays: [20,40,60,80]
gamma: 0.5
test_every: 1
log_lines: 10
log_path: "./experiments"

log_name:
cloudlog: off
repeat: 1
augment: 'off'

# produce
model_path: 'experiments/pred-geonet-2024-0604-1519-4420/models/model_latest.pt'
save_path: "./save_dir"
current: 12

## hardware specification
# specify the GPUs you want to use. [0] means using the first GPU. [1,3] means using second and fourth GPU
gpu_ids: [0]
#gpu_ids: ''
threads: 0
## data specification
# the path train and test dateset. You can download the dataset in this project
pred_data_path: './dataset'
prec_data_path: './dataset'
split_size: 100
