model: 'geonet'
task: 'pred'
downstage: 4
c_in: 7
p_step: 12
n_lgab: 16
c_lgan: 90
window_sizes: [ 5,10]
num_heads: 4
down_sample: 2
r_expand: 2
## hardware specification
# specify the GPUs you want to use. [0] means using the first GPU. [1,3] means using second and fourth GPU
#gpu_ids: [ 3,0,1,2 ]
gpu_ids: [0]